Tmp dev
MGXlab/DNNGIOR pull request #13
Opened 2023-09-18 12:26 UTC by hariszaf

This PR aims at solving the conflicts between the `develop` and the `main` branch. 
Once merged, both branches will share the pip-oriented architecture of the repo. 
@Biomerene please make sure your last edits have been included in this PR.

2023-09-20 09:25 UTC, Biomerene commented on docs/NN/NN_CM.h5
This is the same as NN_BG, also old savetype

2023-09-20 09:34 UTC, Biomerene commented on docs/NN/NN_CM.h5
I am a bit confused, is files where the NN should be thats used in the package and docs is more like additional stuff, in which case the h5 and npz files should be reversed

2023-09-20 09:55 UTC, hariszaf commented on docs/NN/NN_CM.h5
In the `pip` version, we include all that is under the `dnngior` folder. 
The `docs` are as extra. 
You can check the `develop` branch. 
This leads to the following:

```
>>> import dnngior
>>> dnngior.TRAINED_NN_MSEED
'/home/luna.kuleuven.be/u0156635/.local/lib/python3.10/site-packages/dnngior/files/NN/NN_MS.h5'
```

Is this ok?


> This is the same as NN_BG, also old savetype
You mean it's the old file..? I am not sure I m following.

2023-09-20 10:05 UTC, Biomerene requested changes
there are some old network files and the tutorials might not be right atm but most of it looks fine this way, there are also some empty init files but I am not sure if that is supposed to be that way. The only consideration (but this might be easier after merging) is that it could be nice to be able to still load the old kind of networks if people want (right now NN_Predictor only has the possibility of loading the old one) and maybe using custom scores for gap-filling (but I think we discarded this idea earlier)

2023-09-20 10:05 UTC, Biomerene commented on dnngior/gapfill_class.py
this file changed a lot and most of it is Daniels code but as far as I can tell its fine

2023-09-20 10:11 UTC, hariszaf commented on README.md
The notebooks will be cleaned after this major PR. 
We have this one [here] that I think is the latest one. 

Could you please tell me if we can merge the PR and then remove the networks that are old or if there's a network in the `main` branch that is newer and I have not included in the PR ?

2023-09-20 10:11 UTC, Biomerene commented on docs/NN/NN_CM.h5
Sorry, I should be more specific. I changed from the old h5 files (which saves a lot of additional information required if you want to do more training etc.) to a much simpler npz files for the network (which only contains the information required to make predictions using matrix multiplication). The idea would be that this would make the package smaller and if you just want to make predictions and do NN guided gap-filling this is all you need. This would mean that the npz files should be in the dnngior folder and the h5 files in the docs for if people still want the full version

2023-09-20 10:11 UTC, Biomerene commented on docs/NN/NN_CM.h5
I do just realise that it is not actually still possible to load those networks using the NN Predictor class but that might be fine

2023-09-20 10:22 UTC, Biomerene commented on README.md
we can merge and then remove, I forgot that that would be easier

2023-09-20 10:29 UTC, Biomerene approved these changes

2023-09-25 15:56 UTC, hariszaf commented
Daniel said he approves so let's merge!

2023-09-25 15:56 UTC, merged